import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by `flutterfire configure`

import 'screens/reset_password_screen.dart';
import 'screens/login_screen.dart';
import 'screens/admin_dashboard_screen.dart';
import 'screens/admin_system_logs_screen.dart';
import 'screens/users_management_screen.dart';
import 'screens/admin_notifications_screen.dart';
import 'screens/admin_settings_screen.dart';
import 'screens/superadmin_notifications_screen.dart';
import 'screens/superadmin_dashboard_screen.dart';
import 'screens/admin_management_screen.dart';
import 'screens/superadmin_settings_screen.dart';
import 'screens/superadmin_system_logs_screen.dart';

// Add go_router dependency to your pubspec.yaml:
// go_router: ^13.0.0 (or latest stable)

import 'package:go_router/go_router.dart';

final GoRouter _router = GoRouter(
  initialLocation: '/login',
  routes: [
    GoRoute(
      path: '/reset-password',
      builder: (context, state) {
        final token = state.uri.queryParameters['token'];
        return ResetPasswordScreen(token: token);
      },
    ),
    GoRoute(
      path: '/login',
      builder: (context, state) => const LoginScreen(),
    ),
    GoRoute(
      path: '/dashboard',
      builder: (context, state) => const DashboardScreen(),
    ),
    GoRoute(
      path: '/admin-system-logs',
      builder: (context, state) => const AdminSystemLogsScreen(),
    ),
    GoRoute(
      path: '/users',
      builder: (context, state) => const UsersScreen(),
    ),
    GoRoute(
      path: '/notifications',
      builder: (context, state) => const NotificationsScreen(),
    ),
    GoRoute(
      path: '/settings',
      builder: (context, state) => const SettingsScreen(),
    ),
    GoRoute(
      path: '/superadmin-dashboard',
      builder: (context, state) => const SuperAdminDashboardScreen(),
    ),
    GoRoute(
      path: '/admins',
      builder: (context, state) =>
          const AdminManagementScreen(role: 'superadmin'),
    ),
    GoRoute(
      path: '/superadmin-notifications',
      builder: (context, state) => const SuperAdminNotificationsScreen(),
    ),
    GoRoute(
      path: '/superadmin-settings',
      builder: (context, state) => const SuperadminSettingsScreen(),
    ),
    GoRoute(
      path: '/superadmin-system-logs',
      builder: (context, state) => const SuperAdminSystemLogsScreen(),
    ),
  ],
  errorBuilder: (context, state) => const LoginScreen(),
);

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const AdminDashboardApp());
}

class AdminDashboardApp extends StatelessWidget {
  const AdminDashboardApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
      title: 'CDRRMO Admin Dashboard',
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.green,
        primaryColor: const Color(0xFF13b464),
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF13b464),
          brightness: Brightness.light,
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF13b464),
          foregroundColor: Colors.white,
          elevation: 2,
          centerTitle: true,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF13b464),
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            elevation: 2,
          ),
        ),
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            foregroundColor: const Color(0xFF13b464),
            side: const BorderSide(color: Color(0xFF13b464)),
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFFb6fcd5)),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFFb6fcd5)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFF13b464), width: 2),
          ),
          errorBorder: const OutlineInputBorder(
            borderSide: BorderSide(color: Colors.red),
          ),
          focusedErrorBorder: const OutlineInputBorder(
            borderSide: BorderSide(color: Colors.red, width: 2),
          ),
          filled: true,
          fillColor: const Color(0xFFeafaf3),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 16,
            vertical: 16,
          ),
        ),
        cardTheme: const CardThemeData(
          color: Color(0xFFeafaf3),
          elevation: 2,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
        ),
        drawerTheme: const DrawerThemeData(
          backgroundColor: Color(0xFF183c2b),
          elevation: 4,
        ),
        listTileTheme: const ListTileThemeData(
          textColor: Color(0xFF13b464),
          iconColor: Color(0xFF13b464),
        ),
        dataTableTheme: DataTableThemeData(
          headingRowColor: WidgetStateProperty.all(const Color(0xFF13b464)),
          headingTextStyle: const TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.bold,
          ),
          dataRowColor: WidgetStateProperty.all(const Color(0xFFeafaf3)),
          columnSpacing: 24,
          horizontalMargin: 16,
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      debugShowCheckedModeBanner: false,
    );
  }
}
