import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by `flutterfire configure`

import 'screens/login_screen.dart';
import 'screens/admin_dashboard_screen.dart';
import 'screens/admin_system_logs_screen.dart';
import 'screens/users_management_screen.dart';
import 'screens/admin_notifications_screen.dart';
import 'screens/admin_settings_screen.dart';
import 'screens/superadmin_notifications_screen.dart';
import 'screens/superadmin_dashboard_screen.dart';
import 'screens/admin_management_screen.dart';
import 'screens/superadmin_settings_screen.dart';
import 'screens/superadmin_system_logs_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const AdminDashboardApp());
}

class AdminDashboardApp extends StatelessWidget {
  const AdminDashboardApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CDRRMO Admin Dashboard',
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.green,
        primaryColor: const Color(0xFF13b464),
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF13b464),
          brightness: Brightness.light,
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF13b464),
          foregroundColor: Colors.white,
          elevation: 2,
          centerTitle: true,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF13b464),
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            elevation: 2,
          ),
        ),
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            foregroundColor: const Color(0xFF13b464),
            side: const BorderSide(color: Color(0xFF13b464)),
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFFb6fcd5)),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFFb6fcd5)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFF13b464), width: 2),
          ),
          errorBorder: const OutlineInputBorder(
            borderSide: BorderSide(color: Colors.red),
          ),
          focusedErrorBorder: const OutlineInputBorder(
            borderSide: BorderSide(color: Colors.red, width: 2),
          ),
          filled: true,
          fillColor: const Color(0xFFeafaf3),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 16,
            vertical: 16,
          ),
        ),
        cardTheme: const CardThemeData(
          color: Color(0xFFeafaf3),
          elevation: 2,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
        ),
        drawerTheme: const DrawerThemeData(
          backgroundColor: Color(0xFF183c2b),
          elevation: 4,
        ),
        listTileTheme: const ListTileThemeData(
          textColor: Color(0xFF13b464),
          iconColor: Color(0xFF13b464),
        ),
        dataTableTheme: DataTableThemeData(
          headingRowColor: WidgetStateProperty.all(const Color(0xFF13b464)),
          headingTextStyle: const TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.bold,
          ),
          dataRowColor: WidgetStateProperty.all(const Color(0xFFeafaf3)),
          columnSpacing: 24,
          horizontalMargin: 16,
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      initialRoute: '/',
      routes: {
        '/login': (context) => const LoginScreen(),
        '/dashboard': (context) => const DashboardScreen(),
        '/admin-system-logs': (context) => const AdminSystemLogsScreen(),
        '/users': (context) => const UsersScreen(),
        '/notifications': (context) => const NotificationsScreen(),
        '/settings': (context) => const SettingsScreen(),
        '/superadmin-dashboard': (context) => const SuperAdminDashboardScreen(),
        '/admins': (context) => const AdminManagementScreen(role: 'superadmin'),
        '/superadmin-notifications': (context) =>
            const SuperAdminNotificationsScreen(),
        '/superadmin-settings': (context) => const SuperadminSettingsScreen(),
        '/superadmin-system-logs': (context) =>
            const SuperAdminSystemLogsScreen(),
      },
      onUnknownRoute: (settings) {
        return MaterialPageRoute(builder: (context) => const LoginScreen());
      },
      debugShowCheckedModeBanner: false,
    );
  }
}
